import { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getShare } from "@/lib/share";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ArrowRight, Clock, Share2 } from "lucide-react";
import ReactMarkdown from "react-markdown";

interface Props {
  params: Promise<{ id: string }>;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params;
  const share = await getShare(id);

  if (!share) {
    return {
      title: "Result Not Found | AI Marketing Skills",
    };
  }

  return {
    title: `${share.skillName} Result | AI Marketing Skills`,
    description: `View this ${share.skillName} output generated by AI Marketing Skills.`,
    openGraph: {
      title: `${share.skillName} Result`,
      description: `View this ${share.skillName} output generated by AI Marketing Skills.`,
    },
  };
}

export default async function SharedResultPage({ params }: Props) {
  const { id } = await params;
  const share = await getShare(id);

  if (!share) {
    notFound();
  }

  const createdDate = new Date(share.createdAt);
  const expiresDate = new Date(share.expiresAt);
  const daysUntilExpiry = Math.ceil(
    (expiresDate.getTime() - Date.now()) / (1000 * 60 * 60 * 24)
  );

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 sticky top-0 z-50">
        <div className="container mx-auto px-4 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2 font-bold text-xl">
            <span className="text-2xl">🔱</span>
            <span>AI Marketing Skills</span>
          </Link>
          <Button asChild>
            <Link href={`/playground/${share.skillId}`}>
              Run Your Own
              <ArrowRight className="ml-2 h-4 w-4" />
            </Link>
          </Button>
        </div>
      </header>

      {/* Main content */}
      <main className="container mx-auto px-4 py-8 max-w-4xl">
        {/* Info banner */}
        <div className="bg-muted/50 border rounded-lg p-4 mb-6 flex items-center justify-between flex-wrap gap-4">
          <div className="flex items-center gap-4">
            <Share2 className="h-5 w-5 text-muted-foreground" />
            <div>
              <p className="font-medium">Shared Result</p>
              <p className="text-sm text-muted-foreground">
                Created {createdDate.toLocaleDateString()}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Clock className="h-4 w-4" />
            <span>Expires in {daysUntilExpiry} days</span>
          </div>
        </div>

        {/* Result card */}
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <div>
                <CardTitle>{share.skillName}</CardTitle>
                <CardDescription>
                  Generated output from AI Marketing Skills
                </CardDescription>
              </div>
              <Badge variant="secondary">Read Only</Badge>
            </div>
          </CardHeader>
          <CardContent>
            <div className="prose prose-sm dark:prose-invert max-w-none">
              <ReactMarkdown>{share.output}</ReactMarkdown>
            </div>
          </CardContent>
        </Card>

        {/* CTA */}
        <div className="mt-8 text-center">
          <p className="text-muted-foreground mb-4">
            Want to generate your own? It&apos;s free!
          </p>
          <div className="flex justify-center gap-4">
            <Button asChild size="lg">
              <Link href={`/playground/${share.skillId}`}>
                Try {share.skillName}
                <ArrowRight className="ml-2 h-4 w-4" />
              </Link>
            </Button>
            <Button asChild variant="outline" size="lg">
              <Link href="/playground">View All Skills</Link>
            </Button>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t py-8 mt-12">
        <div className="container mx-auto px-4 text-center text-sm text-muted-foreground">
          <p>
            Powered by{" "}
            <a
              href="https://intelliagent.com.au"
              target="_blank"
              rel="noopener noreferrer"
              className="underline hover:text-foreground"
            >
              IntelliAgent
            </a>
          </p>
        </div>
      </footer>
    </div>
  );
}
